=== SimicSvetislav/megaTravel/agentBackend/src/main/resources/schemas/Rezervacija.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.model.megatravel.project.com/reservations"
    xmlns="www.model.megatravel.project.com/reservations"
    xmlns:acc="www.model.megatravel.project.com/accomodation"
    xmlns:usr="www.model.megatravel.project.com/users" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    jxb:version="2.1">
    <xs:import namespace="www.model.megatravel.project.com/users" schemaLocation="KorisnikSema.xsd"/>
    <xs:import namespace="www.model.megatravel.project.com/accomodation"
        schemaLocation="SmestajSema.xsd"/>
    <xs:complexType name="TKomentar">
        <xs:annotation>
            <xs:appinfo>
                <jxb:class name="Komentar"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="tekst">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1024"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="prilog" type="xs:anyType"/>
            <xs:element default="false" name="odobren" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TRezervacija">
        <xs:annotation>
            <xs:appinfo>
                <jxb:class name="TRezervacija"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="datumPocetka">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:appinfo>
                            <jxb:javaType name="java.util.Date" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDate" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDate"/>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:restriction base="xs:date">
                        <xs:minInclusive value="1900-01-01"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datumZavrsetka">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:appinfo>
                            <jxb:javaType name="java.util.Date" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDate" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDate"/>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:restriction base="xs:date">
                        <xs:minInclusive value="1900-01-01"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="popust">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="smestajnaJedinica">
                <xs:annotation>
                    <xs:appinfo>
                        <jxb:javaType name="java.lang.Long" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseLong" printMethod="com.project.megatravel.util.MyDatatypeConverter.printLong"/>
                    </xs:appinfo>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id">
            <xs:simpleType>
                <xs:restriction base="xs:long">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="RezervacijaKorisnika">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="TRezervacija">
                    <xs:sequence>
                        <xs:element name="cenaSmestaja">
                            <xs:simpleType>
                                <xs:annotation>
                                    <xs:appinfo>
                                        <jxb:javaType name="java.lang.Double" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDouble" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDouble"/>
                                    </xs:appinfo>
                                </xs:annotation>
                                <xs:restriction base="xs:double"> </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="stanje">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="REZERVISANO"/>
                                    <xs:enumeration value="U TOKU"/>
                                    <xs:enumeration value="OTKAZANO"/>
                                    <xs:enumeration value="REALIZOVANO"/>
                                    <xs:enumeration value="U OBRADI"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="korisnik">
                            <xs:annotation>
                                <xs:appinfo>
                                    <jxb:javaType name="java.lang.Long" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseLong" printMethod="com.project.megatravel.util.MyDatatypeConverter.printLong"/>
                                </xs:appinfo>
                            </xs:annotation>
                            <xs:simpleType>
                                <xs:restriction base="xs:long">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element default="false" name="ocenjeno" type="xs:boolean"/>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="dodatneUsluge">
                            <xs:annotation>
                                <xs:appinfo>
                                    <jxb:javaType name="java.lang.Long" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseLong" printMethod="com.project.megatravel.util.MyDatatypeConverter.printLong"/>
                                </xs:appinfo>
                            </xs:annotation>
                            <xs:simpleType>
                                <xs:restriction base="xs:long">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="datumRezervacije">
                        <xs:simpleType>
                            <xs:annotation>
                                <xs:appinfo>
                                <jxb:javaType name="java.util.Date" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDate" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDate"/>
                            </xs:appinfo>
                            </xs:annotation>
                            <xs:restriction base="xs:date">
                                <xs:minInclusive value="1900-01-01"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SimicSvetislav/megaTravel/podaci/kolekcije/rezervacije/rezervacijaTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<res:RezervacijaKorisnika xmlns:acc="www.model.megatravel.project.com/accomodation"
 xmlns:res="www.model.megatravel.project.com/reservations"
 xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:usr="www.model.megatravel.project.com/users"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.model.megatravel.project.com/reservations file:/C:/Users/lukaj/git/megaTravel/schemas_ws/Rezervacija.xsd" datumRezervacije="2006-05-04" id="50">
    <res:datumPocetka>2006-05-04</res:datumPocetka>
    <res:datumZavrsetka>2006-05-04</res:datumZavrsetka>
    <res:popust>0.5</res:popust>
    <res:smestajnaJedinica>50</res:smestajnaJedinica>
    <res:cenaSmestaja>0</res:cenaSmestaja>
    <res:stanje>REZERVISANO</res:stanje>
    <res:korisnik>50</res:korisnik>
    <res:ocenjeno>false</res:ocenjeno>
</res:RezervacijaKorisnika>
