=== SimicSvetislav/megaTravel/backend-main/mega-travel/data/schemas/KorisnikSema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.model.megatravel.project.com/users"
    xmlns="www.model.megatravel.project.com/users"
    xmlns:acc="www.model.megatravel.project.com/accomodation"
    xmlns:res="www.model.megatravel.project.com/reservations"
    xmlns:usr="www.model.megatravel.project.com/users" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    jxb:version="2.1">
    <xs:import schemaLocation="SmestajSema.xsd"
        namespace="www.model.megatravel.project.com/accomodation"/>
    <xs:import namespace="www.model.megatravel.project.com/reservations"
        schemaLocation="Rezervacija.xsd"/>
    <xs:complexType abstract="true" name="TKorisnik">
        <xs:annotation>
            <xs:appinfo>
                <jxb:class name="TKorisnik"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="korisnickoIme">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="64"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="sifra">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="64"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern
                            value="^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$"/>
                        <xs:maxLength value="64"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="adresa">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="128"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="telefon">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="32"/>
                        <xs:pattern value="[+]?\d{9,15}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id">
            <xs:simpleType>
                <xs:restriction base="xs:long">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="datumRegistracije">
            <xs:simpleType>
                <xs:annotation>
                    <xs:appinfo>
                        <jxb:javaType name="java.util.Date" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDate" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDate"/>
                    </xs:appinfo>
                </xs:annotation>
                <xs:restriction base="xs:date">
                    <xs:minInclusive value="1900-01-01"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="TKupon">
        <xs:annotation>
            <xs:appinfo>
                <jxb:class name="Kupon"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="tip">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="GOLD"/>
                        <xs:enumeration value="PLATINUM"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="KrajnjiKorisnik">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="TKorisnik">
                    <xs:sequence>
                        <xs:element default="NA" name="kategorija">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="BRONZE"/>
                                    <xs:enumeration value="SILVER"/>
                                    <xs:enumeration value="GOLD"/>
                                    <xs:enumeration value="PLATINUM"/>
                                    <xs:enumeration value="NA"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element default="false" name="ponudjenPopustNakonOtkazivanja"
                            type="xs:boolean"/>
                        <xs:element name="lokacija" type="acc:TLokacija"/>
                        <xs:element name="ime">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="64"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="prezime">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="64"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="stanje" default="AKTIVAN">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="AKTIVAN"/>
                                    <xs:enumeration value="BLOKIRAN"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="rezervacije">
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="res:TRezervacija">
                                        <xs:sequence>
                                            <xs:element name="cenaSmestaja">
                                                <xs:simpleType>
                                                  <xs:restriction base="xs:double">
                                                  </xs:restriction>
                                                </xs:simpleType>
                                            </xs:element>
                                            <xs:element name="stanje">
                                                <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:enumeration value="REZERVISANO"/>
                                                  <xs:enumeration value="U TOKU"/>
                                                  <xs:enumeration value="OTKAZANO"/>
                                                  <xs:enumeration value="REALIZOVANO"/>
                                                  <xs:enumeration value="U OBRADI"/>
                                                  </xs:restriction>
                                                </xs:simpleType>
                                            </xs:element>
                                            <xs:element name="korisnik" type="TKorisnik"/>
                                            <xs:element name="ocena" type="xs:int"/>
                                            <xs:element name="komentar" type="res:TKomentar"/>
                                            <xs:element default="false" name="obradjeno"
                                                type="xs:boolean"/>
                                        </xs:sequence>
                                        <xs:attribute name="datumRezervacije">
                                            <xs:simpleType>
                                                <xs:annotation>
                                                  <xs:appinfo>
                                <jxb:javaType name="java.util.Date" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDate" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDate"/>
                            </xs:appinfo>
                                                </xs:annotation>
                                                <xs:restriction base="xs:date">
                                                  <xs:minInclusive value="1900-01-01"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="kuponi" type="TKupon"
                        />
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Agent">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="TKorisnik">
                    <xs:sequence>
                        <xs:element name="poslovniMaticniBroj">
                            <xs:simpleType>
                                <xs:annotation>
                                    <xs:appinfo>
                                        <jxb:javaType name="java.lang.Long" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseLong" printMethod="com.project.megatravel.util.MyDatatypeConverter.printLong"/>
                                    </xs:appinfo>
                                </xs:annotation>
                                <xs:restriction base="xs:long">
                                    <xs:minInclusive value="1000000000"/>
                                    <xs:totalDigits value="10"/>
                                    <xs:maxInclusive value="9999999999"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="ime" type="xs:string"/>
                        <xs:element name="prezime" type="xs:string"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Administrator">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="TKorisnik">
                    <xs:sequence>
                        <xs:element name="ime">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="64"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="prezime">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="64"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SimicSvetislav/megaTravel/podaci/kolekcije/agenti/agentTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<usr:Agent xmlns:acc="www.model.megatravel.project.com/accomodation"
 xmlns:res="www.model.megatravel.project.com/reservations"
 xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:usr="www.model.megatravel.project.com/users"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.model.megatravel.project.com/users file:/C:/Users/lukaj/git/megaTravel/schemas_ws/KorisnikSema.xsd">
    <usr:korisnickoIme>korisnickoIme0</usr:korisnickoIme>
    <usr:sifra>sifra0</usr:sifra>
    <usr:email>^-@-.AA$</usr:email>
    <usr:adresa>adresa0</usr:adresa>
    <usr:telefon>000000000</usr:telefon>
    <usr:poslovniMaticniBroj>500000000</usr:poslovniMaticniBroj>
    <usr:ime>ime0</usr:ime>
    <usr:prezime>prezime0</usr:prezime>
</usr:Agent>

=== SimicSvetislav/megaTravel/podaci/kolekcije/admini/adminTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<usr:Administrator xmlns:acc="www.model.megatravel.project.com/accomodation"
 xmlns:res="www.model.megatravel.project.com/reservations"
 xmlns:usr="www.model.megatravel.project.com/users"
 xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.model.megatravel.project.com/users file:/C:/Users/lukaj/git/megaTravel/schemas_ws/KorisnikSema.xsd">
    <usr:korisnickoIme>korisnickoIme0</usr:korisnickoIme>
    <usr:sifra>sifra0</usr:sifra>
    <usr:email>^-@-.AA$</usr:email>
    <usr:adresa>adresa0</usr:adresa>
    <usr:telefon>000000000</usr:telefon>
    <usr:ime>ime0</usr:ime>
    <usr:prezime>prezime0</usr:prezime>
</usr:Administrator>
