=== SimicSvetislav/megaTravel/agentBackend/data/schemas/SmestajSema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="www.model.megatravel.project.com/accomodation"
    xmlns="www.model.megatravel.project.com/accomodation"
    xmlns:acc="www.model.megatravel.project.com/accomodation"
    xmlns:res="www.model.megatravel.project.com/reservations"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.1"
    xmlns:usr="www.model.megatravel.project.com/users">

    <xs:import namespace="www.model.megatravel.project.com/reservations"
        schemaLocation="Rezervacija.xsd"/>
    <xs:import namespace="www.model.megatravel.project.com/users" schemaLocation="KorisnikSema.xsd"/>
    <xs:complexType name="TLokacija">
        <xs:annotation>
            <xs:appinfo>
                <jxb:class name="Lokacija"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="naziv">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="128"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="geoSirina" type="TPolozaj"/>
            <xs:element name="geoDuzina" type="TPolozaj"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TRejting">
        <xs:annotation>
            <xs:appinfo>
                <jxb:class name="Rejting"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="brojOcena">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="sumaOcena">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TCenovnik">
        <xs:annotation>
            <xs:appinfo>
                <jxb:class name="Cenovnik"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="pocetak">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:appinfo>
                            <jxb:javaType name="java.util.Date" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDate" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDate"/>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:restriction base="xs:date">
                        <xs:minInclusive value="1900-01-01"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="kraj">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:appinfo>
                            <jxb:javaType name="java.util.Date" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDate" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDate"/>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:restriction base="xs:date">
                        <xs:minInclusive value="1900-01-01"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="cena">
                <xs:annotation>
                    <xs:appinfo>
                        <jxb:javaType name="java.lang.Long" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseLong" printMethod="com.project.megatravel.util.MyDatatypeConverter.printLong"/>
                    </xs:appinfo>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="smestaj">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:appinfo>
                            <jxb:javaType name="java.lang.Long" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseLong" printMethod="com.project.megatravel.util.MyDatatypeConverter.printLong"/>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TOtkazivanje">
        <xs:annotation>
            <xs:appinfo>
                <jxb:class name="Otkazivanje"/>
            </xs:appinfo>
        </xs:annotation>
        <xs:sequence>
            <xs:element default="false" name="dozvoljeno" type="xs:boolean"/>
            <xs:element name="brojDana">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="faktorOtkazivanja">
                <xs:simpleType>
                    <xs:restriction base="xs:double">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="SmestajnaJedinica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="brojKreveta">
                    <xs:annotation>
                        <xs:appinfo>
                            <jxb:javaType name="java.lang.Integer" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseInteger" printMethod="com.project.megatravel.util.MyDatatypeConverter.printInteger"/>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element default="false" name="balkon" type="xs:boolean"/>
                <xs:element name="sObjekat" type="xs:long"/>
                <xs:element name="opis">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="1024"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="otkazivanje" type="TOtkazivanje"/>
            </xs:sequence>
            <xs:attribute name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="SmestajniObjekat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lokacija" type="TLokacija"/>
                <xs:element default="NA" name="kategorija">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="BRONZE"/>
                            <xs:enumeration value="SILVER"/>
                            <xs:enumeration value="GOLD"/>
                            <xs:enumeration value="PLATINUM"/>
                            <xs:enumeration value="NA"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="agent">
                    <xs:simpleType>
                        <xs:annotation>
                            <xs:appinfo>
                                <jxb:javaType name="java.lang.Long" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseLong" printMethod="com.project.megatravel.util.MyDatatypeConverter.printLong"/>
                            </xs:appinfo>
                        </xs:annotation>
                        <xs:restriction base="xs:long">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="SmestajnaJedinica"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="DodatnaUsluga"/>
                <xs:element maxOccurs="unbounded" name="slike">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="value">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"/>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="putanja">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string"/>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="tipSmestaja"/>
                <xs:element ref="kategorijaSm"/>
                <xs:element maxOccurs="unbounded" name="cenovnici" type="TCenovnik"/>
                <xs:element name="podrazumevaniCenovnik" type="TCenovnik"/>
            </xs:sequence>
            <xs:attribute name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="zvezdice">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:appinfo>
                            <jxb:javaType name="java.lang.Integer" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseInteger" printMethod="com.project.megatravel.util.MyDatatypeConverter.printInteger"/>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="DodatnaUsluga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cena">
                    <xs:simpleType>
                        <xs:annotation>
                            <xs:appinfo>
                                <jxb:javaType name="java.lang.Double" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDouble" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDouble"/>
                            </xs:appinfo>
                        </xs:annotation>
                        <xs:restriction base="xs:double">
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="64"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="jedinicaPlacanja">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="PO_DANU"/>
                            <xs:enumeration value="PO_OSOBI"/>
                            <xs:enumeration value="UKUPNO"/>
                            <xs:enumeration value="PO_DANU_PO_OSOBI"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="tipSmestaja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="naziv"/>
            </xs:sequence>
            <xs:attribute name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="kategorijaSm">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zvezdice">
                    <xs:simpleType>
                        <xs:annotation>
                            <xs:appinfo>
                                <jxb:javaType name="java.lang.Integer" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseInteger" printMethod="com.project.megatravel.util.MyDatatypeConverter.printInteger"/>
                            </xs:appinfo>
                        </xs:annotation>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:long">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPolozaj">
        <xs:sequence>
            <xs:element name="stepeni">
                <xs:simpleType>
                    <xs:annotation>
                        <xs:appinfo>
                            <jxb:javaType name="java.lang.Double" parseMethod="com.project.megatravel.util.MyDatatypeConverter.parseDouble" printMethod="com.project.megatravel.util.MyDatatypeConverter.printDouble"/>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:restriction base="xs:double">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="180"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="strana">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="N"/>
                        <xs:enumeration value="S"/>
                        <xs:enumeration value="W"/>
                        <xs:enumeration value="E"/>
                        <xs:length value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== SimicSvetislav/megaTravel/podaci/kolekcije/jedinice/4.xml
<SmestajnaJedinica xmlns="www.model.megatravel.project.com/accomodation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="4" xsi:schemaLocation="https://www.model.megatravel.project.com/accomodation schemas/SmestajSema.xsd">
    <brojKreveta>3</brojKreveta>
    <balkon>true</balkon>
    <sObjekat>3</sObjekat>
    <opis>Ova prostrana soba dovoljna je za 3 odrasle osobe kao porodice sa malom decom.</opis>
    <otkazivanje>
        <dozvoljeno>true</dozvoljeno>
        <brojDana>5</brojDana>
        <faktorOtkazivanja>0.0</faktorOtkazivanja>
    </otkazivanje>
    <oznaka>K1</oznaka>
</SmestajnaJedinica>

=== SimicSvetislav/megaTravel/podaci/kolekcije/jedinice/7.xml
<SmestajnaJedinica xmlns="www.model.megatravel.project.com/accomodation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="7" xsi:schemaLocation="https://www.model.megatravel.project.com/accomodation schemas/SmestajSema.xsd">
    <brojKreveta>3</brojKreveta>
    <balkon>true</balkon>
    <sObjekat>4</sObjekat>
    <opis>Prostrana soba dovoljno velika da se 3 odrasle osobe komotno smeste.</opis>
    <otkazivanje>
        <dozvoljeno>false</dozvoljeno>
        <brojDana>0</brojDana>
        <faktorOtkazivanja>0.0</faktorOtkazivanja>
    </otkazivanje>
    <oznaka>Soba 101</oznaka>
</SmestajnaJedinica>

=== SimicSvetislav/megaTravel/podaci/kolekcije/jedinice/jedinicaTemplate1.xml
<?xml version="1.0" encoding="UTF-8"?>
<acc:SmestajnaJedinica xmlns:acc="www.model.megatravel.project.com/accomodation"
 xmlns:usr="www.model.megatravel.project.com/users"
 xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:res="www.model.megatravel.project.com/reservations"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.model.megatravel.project.com/accomodation file:/C:/Users/lukaj/git/megaTravel/schemas_ws/SmestajSema.xsd" id="50">
    <acc:brojKreveta>50</acc:brojKreveta>
    <acc:balkon>false</acc:balkon>
    <acc:sObjekat>-1073741773</acc:sObjekat>
    <acc:opis>opis0</acc:opis>
    <acc:otkazivanje>
        <acc:dozvoljeno>false</acc:dozvoljeno>
        <acc:brojDana>50</acc:brojDana>
        <acc:faktorOtkazivanja>0.5</acc:faktorOtkazivanja>
    </acc:otkazivanje>
    <acc:oznaka>oznaka0</acc:oznaka>
</acc:SmestajnaJedinica>

=== SimicSvetislav/megaTravel/podaci/kolekcije/jedinice/8.xml
<SmestajnaJedinica xmlns="www.model.megatravel.project.com/accomodation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="8" xsi:schemaLocation="https://www.model.megatravel.project.com/accomodation schemas/SmestajSema.xsd">
    <brojKreveta>3</brojKreveta>
    <balkon>false</balkon>
    <sObjekat>4</sObjekat>
    <otkazivanje>
        <dozvoljeno>true</dozvoljeno>
        <brojDana>5</brojDana>
        <faktorOtkazivanja>0.0</faktorOtkazivanja>
    </otkazivanje>
    <oznaka>Soba 102</oznaka>
</SmestajnaJedinica>

=== SimicSvetislav/megaTravel/podaci/kolekcije/objekti/objekatTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<acc:SmestajniObjekat xmlns:acc="www.model.megatravel.project.com/accomodation"
 xmlns:usr="www.model.megatravel.project.com/users"
 xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:res="www.model.megatravel.project.com/reservations"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="www.model.megatravel.project.com/accomodation file:/C:/Users/lukaj/git/megaTravel/schemas_ws/SmestajSema.xsd" id="50" zvezdice="50">
    <acc:lokacija>
        <acc:naziv>naziv0</acc:naziv>
        <acc:geoSirina>
            <acc:stepeni>90</acc:stepeni>
            <acc:strana>N</acc:strana>
        </acc:geoSirina>
        <acc:geoDuzina>
            <acc:stepeni>90</acc:stepeni>
            <acc:strana>N</acc:strana>
        </acc:geoDuzina>
    </acc:lokacija>
    <acc:kategorija>NA</acc:kategorija>
    <acc:agent>50</acc:agent>
    <acc:SmestajnaJedinica id="50">
        <acc:brojKreveta>50</acc:brojKreveta>
        <acc:balkon>false</acc:balkon>
        <acc:sObjekat>-1073741773</acc:sObjekat>
        <acc:opis>opis0</acc:opis>
        <acc:otkazivanje>
            <acc:dozvoljeno>false</acc:dozvoljeno>
            <acc:brojDana>50</acc:brojDana>
            <acc:faktorOtkazivanja>0.5</acc:faktorOtkazivanja>
        </acc:otkazivanje>
        <acc:oznaka>oznaka0</acc:oznaka>
    </acc:SmestajnaJedinica>
    <acc:SmestajnaJedinica id="50">
        <acc:brojKreveta>50</acc:brojKreveta>
        <acc:balkon>false</acc:balkon>
        <acc:sObjekat>-1073741773</acc:sObjekat>
        <acc:opis>opis1</acc:opis>
        <acc:otkazivanje>
            <acc:dozvoljeno>false</acc:dozvoljeno>
            <acc:brojDana>50</acc:brojDana>
            <acc:faktorOtkazivanja>0.5</acc:faktorOtkazivanja>
        </acc:otkazivanje>
        <acc:oznaka>oznaka1</acc:oznaka>
    </acc:SmestajnaJedinica>
    <acc:DodatnaUsluga id="50">
        <acc:cena>50</acc:cena>
        <acc:ime>ime0</acc:ime>
        <acc:jedinicaPlacanja>PO_DANU</acc:jedinicaPlacanja>
    </acc:DodatnaUsluga>
    <acc:DodatnaUsluga id="50">
        <acc:cena>50</acc:cena>
        <acc:ime>ime1</acc:ime>
        <acc:jedinicaPlacanja>PO_DANU</acc:jedinicaPlacanja>
    </acc:DodatnaUsluga>
    <acc:slike>
        <acc:value>value0</acc:value>
        <acc:putanja>putanja0</acc:putanja>
    </acc:slike>
    <acc:slike>
        <acc:value>value1</acc:value>
        <acc:putanja>putanja1</acc:putanja>
    </acc:slike>
    <acc:tipSmestaja id="50">
        <acc:naziv>
        </acc:naziv>
    </acc:tipSmestaja>
    <acc:kategorijaSm id="50">
        <acc:zvezdice>50</acc:zvezdice>
    </acc:kategorijaSm>
    <acc:cenovnici>
        <acc:pocetak>2006-05-04</acc:pocetak>
        <acc:kraj>2006-05-04</acc:kraj>
        <acc:cena>50</acc:cena>
        <acc:smestaj>50</acc:smestaj>
    </acc:cenovnici>
    <acc:cenovnici>
        <acc:pocetak>2006-05-04</acc:pocetak>
        <acc:kraj>2006-05-04</acc:kraj>
        <acc:cena>50</acc:cena>
        <acc:smestaj>50</acc:smestaj>
    </acc:cenovnici>
    <acc:podrazumevaniCenovnik>
        <acc:pocetak>2006-05-04</acc:pocetak>
        <acc:kraj>2006-05-04</acc:kraj>
        <acc:cena>50</acc:cena>
        <acc:smestaj>50</acc:smestaj>
    </acc:podrazumevaniCenovnik>
    <acc:opis>opis2</acc:opis>
    <acc:naziv>naziv1</acc:naziv>
</acc:SmestajniObjekat>

=== SimicSvetislav/megaTravel/podaci/kolekcije/objekti/Untitled1.xml
<SmestajniObjekat xmlns="www.model.megatravel.project.com/accomodation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="1" zvezdice="4" xsi:schemaLocation="https://www.model.megatravel.project.com/accomodation schemas/SmestajSema.xsd">
    <lokacija>
        <naziv>Novi Sad</naziv>
    </lokacija>
    <kategorija>GOLD</kategorija>
    <agent>1</agent>
    <SmestajnaJedinica id="1">
        <brojKreveta>1</brojKreveta>
        <balkon>true</balkon>
        <sObjekat>1</sObjekat>
        <opis>Soba namenjena za one koji zele da uzivaju u miru, a ipak imaju dovoljno prostora samo za sebe</opis>
        <otkazivanje>
            <dozvoljeno>true</dozvoljeno>
            <brojDana>20</brojDana>
            <faktorOtkazivanja>0.0</faktorOtkazivanja>
        </otkazivanje>
        <oznaka>K1</oznaka>
    </SmestajnaJedinica>
    <SmestajnaJedinica id="2">
        <brojKreveta>3</brojKreveta>
        <balkon>false</balkon>
        <sObjekat>1</sObjekat>
        <opis>Idealna za bracne parove sa decom, bracni krevet dovoljno velik i za malo dete</opis>
        <otkazivanje>
            <dozvoljeno>false</dozvoljeno>
            <brojDana>0</brojDana>
            <faktorOtkazivanja>0.0</faktorOtkazivanja>
        </otkazivanje>
        <oznaka>K2</oznaka>
    </SmestajnaJedinica>
    <SmestajnaJedinica id="3">
        <brojKreveta>5</brojKreveta>
        <balkon>true</balkon>
        <sObjekat>1</sObjekat>
        <opis>Apartman koji poseduje dve sobe sa krevetima</opis>
        <otkazivanje>
            <dozvoljeno>true</dozvoljeno>
            <brojDana>5</brojDana>
            <faktorOtkazivanja>0.0</faktorOtkazivanja>
        </otkazivanje>
        <oznaka>K3</oznaka>
    </SmestajnaJedinica>
    <DodatnaUsluga id="1">
        <cena>200.0</cena>
        <ime>wifi</ime>
        <jedinicaPlacanja>RSD</jedinicaPlacanja>
    </DodatnaUsluga>
    <DodatnaUsluga id="2">
        <cena>200.0</cena>
        <ime>bazen</ime>
        <jedinicaPlacanja>eur</jedinicaPlacanja>
    </DodatnaUsluga>
    <DodatnaUsluga id="3">
        <cena>200.0</cena>
        <ime>room service</ime>
        <jedinicaPlacanja>RSD</jedinicaPlacanja>
    </DodatnaUsluga>
    <DodatnaUsluga id="4">
        <cena>100.0</cena>
        <ime>budjenje</ime>
        <jedinicaPlacanja>RSD</jedinicaPlacanja>
    </DodatnaUsluga>
    <tipSmestaja id="1">
        <naziv xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">hotel</naziv>
    </tipSmestaja>
    <kategorijaSm id="1">
        <zvezdice>0</zvezdice>
    </kategorijaSm>
    <cenovnici>
        <pocetak>2019-04-04</pocetak>
        <kraj>2019-05-04</kraj>
        <cena>200</cena>
        <smestaj>1</smestaj>
    </cenovnici>
    <cenovnici>
        <pocetak>2019-06-06</pocetak>
        <kraj>2019-07-06</kraj>
        <cena>200</cena>
        <smestaj>1</smestaj>
    </cenovnici>
    <podrazumevaniCenovnik>
        <pocetak>2019-04-04</pocetak>
        <kraj>2019-05-04</kraj>
        <cena>200</cena>
        <smestaj>1</smestaj>
    </podrazumevaniCenovnik>
    <opis>Mali udoban porodicni smestaj za bilo koje doba godine. Nasi gosti cine ljudi koji nam se vracaju svake godine iznova i iznova</opis>
    <naziv>Talija</naziv>
</SmestajniObjekat>

=== SimicSvetislav/megaTravel/podaci/kolekcije/jedinice/9.xml
<SmestajnaJedinica xmlns="www.model.megatravel.project.com/accomodation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="9" xsi:schemaLocation="https://www.model.megatravel.project.com/accomodation schemas/SmestajSema.xsd">
    <brojKreveta>5</brojKreveta>
    <balkon>true</balkon>
    <sObjekat>4</sObjekat>
    <opis>Prostrani apartman sa dve zasebne sobe.</opis>
    <otkazivanje>
        <dozvoljeno>true</dozvoljeno>
        <brojDana>5</brojDana>
        <faktorOtkazivanja>0.0</faktorOtkazivanja>
    </otkazivanje>
    <oznaka>Soba 105</oznaka>
</SmestajnaJedinica>
